/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

public class Admin_menu extends javax.swing.JFrame {

    /**
     * Creates new form Admin_menu
     */
    public Admin_menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        lateral.add(panelEstudiante, "estudiante");
        lateral.add(panelDocente, "docente");
        lateral.add(panelCurso, "curso");
        lateral.add(panelCarrera, "carrera");
        lateral.add(panelSede, "sede");
        lateral.add(panelNoticia, "noticia");
        opcionSeleccionada("noticia");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        lateral = new javax.swing.JPanel();
        panelEstudiante = new javax.swing.JPanel();
        btnEstIns = new javax.swing.JButton();
        btnRegEstudiante = new javax.swing.JButton();
        btnEstEsc = new javax.swing.JButton();
        btnEstEditar = new javax.swing.JButton();
        panelDocente = new javax.swing.JPanel();
        panelCarrera = new javax.swing.JPanel();
        panelSede = new javax.swing.JPanel();
        panelNoticia = new javax.swing.JPanel();
        btnEstEditar1 = new javax.swing.JButton();
        btnEstEditar2 = new javax.swing.JButton();
        panelCurso = new javax.swing.JPanel();
        btnEstudiante = new javax.swing.JButton();
        btnDocente = new javax.swing.JButton();
        btnCurso = new javax.swing.JButton();
        btnCarrera = new javax.swing.JButton();
        btnSede = new javax.swing.JButton();
        btnNoticia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principal.setMinimumSize(new java.awt.Dimension(50, 50));
        principal.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lateral.setLayout(new java.awt.CardLayout());

        btnEstIns.setText("<html>Inscribir a Carrera<html>");

        btnRegEstudiante.setText("<html>Registrar<html>");
        btnRegEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegEstudianteActionPerformed(evt);
            }
        });

        btnEstEsc.setText("<html>Escolaridad<html>");

        btnEstEditar.setText("<html>Editar<html>");

        javax.swing.GroupLayout panelEstudianteLayout = new javax.swing.GroupLayout(panelEstudiante);
        panelEstudiante.setLayout(panelEstudianteLayout);
        panelEstudianteLayout.setHorizontalGroup(
            panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstudianteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstIns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstEsc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        panelEstudianteLayout.setVerticalGroup(
            panelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstudianteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnRegEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnEstIns, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstEsc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        lateral.add(panelEstudiante, "card2");

        javax.swing.GroupLayout panelDocenteLayout = new javax.swing.GroupLayout(panelDocente);
        panelDocente.setLayout(panelDocenteLayout);
        panelDocenteLayout.setHorizontalGroup(
            panelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        panelDocenteLayout.setVerticalGroup(
            panelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        lateral.add(panelDocente, "card3");

        javax.swing.GroupLayout panelCarreraLayout = new javax.swing.GroupLayout(panelCarrera);
        panelCarrera.setLayout(panelCarreraLayout);
        panelCarreraLayout.setHorizontalGroup(
            panelCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        panelCarreraLayout.setVerticalGroup(
            panelCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        lateral.add(panelCarrera, "card4");

        javax.swing.GroupLayout panelSedeLayout = new javax.swing.GroupLayout(panelSede);
        panelSede.setLayout(panelSedeLayout);
        panelSedeLayout.setHorizontalGroup(
            panelSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        panelSedeLayout.setVerticalGroup(
            panelSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        lateral.add(panelSede, "card5");

        btnEstEditar1.setText("<html>Crear<html>");
        btnEstEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstEditar1ActionPerformed(evt);
            }
        });

        btnEstEditar2.setText("<html>Editar<html>");

        javax.swing.GroupLayout panelNoticiaLayout = new javax.swing.GroupLayout(panelNoticia);
        panelNoticia.setLayout(panelNoticiaLayout);
        panelNoticiaLayout.setHorizontalGroup(
            panelNoticiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoticiaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelNoticiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelNoticiaLayout.setVerticalGroup(
            panelNoticiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoticiaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnEstEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        lateral.add(panelNoticia, "card6");

        javax.swing.GroupLayout panelCursoLayout = new javax.swing.GroupLayout(panelCurso);
        panelCurso.setLayout(panelCursoLayout);
        panelCursoLayout.setHorizontalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        panelCursoLayout.setVerticalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        lateral.add(panelCurso, "card7");

        btnEstudiante.setText("Estudiante");
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });

        btnDocente.setText("Docente");
        btnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteActionPerformed(evt);
            }
        });

        btnCurso.setText("Curso");
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });

        btnCarrera.setText("Carrera");
        btnCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarreraActionPerformed(evt);
            }
        });

        btnSede.setText("Sede");
        btnSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSedeActionPerformed(evt);
            }
        });

        btnNoticia.setText("Noticias");
        btnNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSede, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNoticia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNoticia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstudiante)
                        .addGap(5, 5, 5)
                        .addComponent(btnDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSede)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteActionPerformed
        opcionSeleccionada("docente");
    }//GEN-LAST:event_btnDocenteActionPerformed

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
        opcionSeleccionada("curso");
    }//GEN-LAST:event_btnCursoActionPerformed

    private void btnCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarreraActionPerformed
        opcionSeleccionada("carrera");
    }//GEN-LAST:event_btnCarreraActionPerformed

    private void btnSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSedeActionPerformed
        opcionSeleccionada("sede");
    }//GEN-LAST:event_btnSedeActionPerformed

    private void btnNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticiaActionPerformed
        opcionSeleccionada("noticia");
    }//GEN-LAST:event_btnNoticiaActionPerformed

    private void btnRegEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegEstudianteActionPerformed
       
    }//GEN-LAST:event_btnRegEstudianteActionPerformed

    private void btnEstEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstEditar1ActionPerformed
        Admin_NuevaNoticia nn = new Admin_NuevaNoticia();
        this.principal.add(nn);
        nn.show();
    }//GEN-LAST:event_btnEstEditar1ActionPerformed

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        opcionSeleccionada("estudiante");
    }//GEN-LAST:event_btnEstudianteActionPerformed

    void opcionSeleccionada(String opcion) {
        CardLayout cl = (CardLayout) (lateral.getLayout());

        switch (opcion) {
            case "curso":
                cl.show(lateral, "curso");
                break;
            case "carrera":
                cl.show(lateral, "carrera");
                break;
            case "sede":;
                cl.show(lateral, "sede");
                break;
            case "estudiante":
                cl.show(lateral, "estudiante");
                break;
            case "docente":
                cl.show(lateral, "docente");
                break;
            case "noticia":;
                cl.show(lateral, "noticia");
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrera;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnDocente;
    private javax.swing.JButton btnEstEditar;
    private javax.swing.JButton btnEstEditar1;
    private javax.swing.JButton btnEstEditar2;
    private javax.swing.JButton btnEstEsc;
    private javax.swing.JButton btnEstIns;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnNoticia;
    private javax.swing.JButton btnRegEstudiante;
    private javax.swing.JButton btnSede;
    private javax.swing.JPanel lateral;
    private javax.swing.JPanel panelCarrera;
    private javax.swing.JPanel panelCurso;
    private javax.swing.JPanel panelDocente;
    private javax.swing.JPanel panelEstudiante;
    private javax.swing.JPanel panelNoticia;
    private javax.swing.JPanel panelSede;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
