/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Curso;
import Clases.Fabrica;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.ListModel;

/**
 *
 * @author Usuario
 */
public class Admin_NuevaNoticia extends javax.swing.JInternalFrame {

    public Admin_NuevaNoticia() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLabel1 = new javax.swing.JLabel();
        TituloLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoTextArea = new javax.swing.JTextArea();
        TituloTextField = new javax.swing.JTextField();
        TituloLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EtiquetasList = new javax.swing.JList<>();
        EtiquetaTextField = new javax.swing.JTextField();
        AgregarButton = new javax.swing.JButton();
        BorrarButton = new javax.swing.JButton();
        CrearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver curso");

        jPanel1.setBackground(new java.awt.Color(73, 202, 114));

        TituloLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloLabel1.setForeground(new java.awt.Color(255, 255, 255));
        TituloLabel1.setText("Título:");

        TituloLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloLabel4.setForeground(new java.awt.Color(255, 255, 255));
        TituloLabel4.setText("Texto:");

        TextoTextArea.setColumns(20);
        TextoTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextoTextArea.setLineWrap(true);
        TextoTextArea.setRows(5);
        jScrollPane1.setViewportView(TextoTextArea);

        TituloLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloLabel2.setForeground(new java.awt.Color(255, 255, 255));
        TituloLabel2.setText("Etiquetas:");

        EtiquetasList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EtiquetasList.setModel(new DefaultListModel());
        EtiquetasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        EtiquetasList.setToolTipText("");
        jScrollPane2.setViewportView(EtiquetasList);

        EtiquetaTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EtiquetaTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EtiquetaTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EtiquetaTextFieldFocusLost(evt);
            }
        });
        EtiquetaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EtiquetaTextFieldKeyReleased(evt);
            }
        });

        AgregarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AgregarButton.setText("Agregar");
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });

        BorrarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BorrarButton.setText("Borrar");
        BorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarButtonActionPerformed(evt);
            }
        });

        CrearButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CrearButton.setText("Crear Noticia");
        CrearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TituloLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TituloLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EtiquetaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BorrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TituloLabel4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CrearButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloLabel1)
                    .addComponent(TituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TituloLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TituloLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BorrarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CrearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EtiquetaTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EtiquetaTextFieldFocusGained
        
    }//GEN-LAST:event_EtiquetaTextFieldFocusGained

    private void EtiquetaTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EtiquetaTextFieldFocusLost
        
    }//GEN-LAST:event_EtiquetaTextFieldFocusLost

    private void EtiquetaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EtiquetaTextFieldKeyReleased

    }//GEN-LAST:event_EtiquetaTextFieldKeyReleased

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
        String etiqueta = EtiquetaTextField.getText();
        
        if(etiqueta.equals("")){
            JOptionPane.showMessageDialog(this, "La etiqueta no puede estar vacía", "Ingresar etiqueta", WARNING_MESSAGE);
        }else{
            boolean repetido = false;
            DefaultListModel modelo = (DefaultListModel) EtiquetasList.getModel();
            for (int i = 0; i < modelo.getSize(); i++) {
                String e = (String) modelo.getElementAt(i);
                if(e.equals(etiqueta)){
                    repetido=true;   
                    break;
                }
            }
            if(repetido){
                JOptionPane.showMessageDialog(this, "Ya ingresó la etiqueta '"+etiqueta+"'", "Etiqueta repetida", WARNING_MESSAGE);
            }else{
                modelo.addElement(etiqueta);
            }
        }
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void BorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButtonActionPerformed
        if(EtiquetasList.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una etiqueta", "Seleccionar etiqueta", WARNING_MESSAGE);
        }else{
            DefaultListModel modelo = (DefaultListModel) EtiquetasList.getModel();
            modelo.removeElementAt(EtiquetasList.getSelectedIndex());
        }
    }//GEN-LAST:event_BorrarButtonActionPerformed

    private void CrearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearButtonActionPerformed
        String titulo = TituloTextField.getText();
        String texto = TextoTextArea.getText();
        
        List etiquetas = new ArrayList();
        DefaultListModel modelo = (DefaultListModel) EtiquetasList.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            String e = (String) modelo.getElementAt(i);
            etiquetas.add(e);
        }
        
        Fabrica.getInstance().getContAdmin().nuevaNoticia(titulo, texto, etiquetas);
    }//GEN-LAST:event_CrearButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JButton BorrarButton;
    private javax.swing.JButton CrearButton;
    private javax.swing.JTextField EtiquetaTextField;
    private javax.swing.JList<String> EtiquetasList;
    private javax.swing.JTextArea TextoTextArea;
    private javax.swing.JLabel TituloLabel1;
    private javax.swing.JLabel TituloLabel2;
    private javax.swing.JLabel TituloLabel4;
    private javax.swing.JTextField TituloTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
